name: Terraform CD

on:
  push:
    branches:
      - master

jobs:
  Terraform:
    name: Infrastructure plan
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: Infrastructure Setup
      uses: hashicorp/setup-terraform@v1

    - name: Infrastructure Init
      run: terraform init
      env:
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Infrastructure validate
      run: terraform validate

    # - name: Infrastructure Plan
    #   run: terraform plan
    #   env:
    #     TF_ACTION_WORKING_DIR: '.'
    #     AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Infrastructure Apply
      run: terraform apply #-auto-approve
      env:
        TF_ACTION_WORKING_DIR: '.'
        AWS_ACCESS_KEY_ID:  ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
